name: Update Aptoide Categories

on:
  schedule:
    - cron: '0 0 * * *' # နေ့တိုင်း auto run မယ်
  workflow_dispatch: # Manual run လို့ရအောင်

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add apps.json
          
          # ပြောင်းလဲမှုရှိမှ အလုပ်လုပ်မယ်
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-update apps.json with latest data"
            # Server ပေါ်က ပြောင်းလဲမှုတွေကို အတင်းကျော်ပြီး push လုပ်ခိုင်းတာ (Force Push)
            git push origin main --force
          else
            echo "No changes to commit"
          fi
